parse:
    url: http://www.cbr.ru/scripts/XML_daily.asp
    method: SAX
server:
    port: 8080
    servlet:
        context-path: /currency-converter
spring:
    datasource:
        #    driver: com.mysql.jdbc.Driver
        #    url: jdbc:mysql://localhost:3306/converter?createDatabaseIfNotExist=true&serverTimezone=UTC
        #    username: root
        #    password: 111222333

        driver: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/currency_converter?serverTimezone=UTC
        username: postgres
        password: 111222333

        changeLogFile: db/changelog/db.changelog-master.xml
        initialization-mode: always
        verbose: true
    http:
        multipart:
            enabled: true
            max-file-size: 50MB
            max-request-size: 50MB
    jpa:
        database: default
        show-sql: true
        open-in-view: false
        generate-ddl: false
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
    liquibase:
        enabled: true
        change-log: classpath:${spring.datasource.changeLogFile}
    flyway:
        enabled: false
