spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/converter
    username: postgres
    password: 111222333
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
